# DFT 2D e FFT 2D

## Índice

1. Introdução
2. Importar imagem e bibliotecas
3. DFT 2D, FFT 2D e Comparação

---

## 1. Introdução

- Feito por: Kenzo Inanami de Faria <br>
- Objetivo:
  - Implemente os algoritmos DFT 2D e FFT 2D para encontrar o espectro de
    Fourier de imagens. Teste as funções na imagem a seguir e compare os tempos de execução: \* https://links.uwaterloo.ca/Repository/TIF/camera.tif
- Fontes:
  - O algoritmo da DFT 2D foi adaptado de: https://dsp.stackexchange.com/questions/66537/2d-dft-in-image-processing-in-python
  - O algoritmo da FFT 2D foi adaptado de: https://jakevdp.github.io/blog/2013/08/28/understanding-the-fft/


## 2. Importar imagem e bibliotecas


In [4]:
import numpy as np
import cv2
import time
import sys
import cmath

In [5]:
# Carregar a imagem usando OpenCV
image = cv2.imread("Imagens/camera.tif", cv2.IMREAD_GRAYSCALE)
if image is None:
  print("Imagem não foi lida, confira se o nome e extensão estão corretos")
  sys.exit(0)

## DFT 2D, FFT 2D e Comparação


In [ ]:
def DFT2D(image):
    data = np.asarray(image)
    M, N = image.shape
    dft2d = np.zeros((M,N),dtype=complex)
    for k in range(M):
        for l in range(N):
            sum_matrix = 0.0
            for m in range(M):
                for n in range(N):
                    e = cmath.exp(- 2j * np.pi * ((k * m) / M + (l * n) / N))
                    sum_matrix +=  data[m,n] * e
            dft2d[k,l] = sum_matrix
    return dft2d



# Medir o tempo de execução da DFT 2D
start_time = time.time()
dft_result = DFT2D(image)
dft_time = time.time() - start_time


print(f"Tempo de execução da DFT 2D: {dft_time:.4f} segundos")

Tempo de execução da DFT 2D: 8760.3017 segundos


In [5]:
def DFT_slow(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    n = np.arange(N)
    k = n.reshape((N, 1))
    M = np.exp(-2j * np.pi * k * n / N)
    return np.dot(M, x)

def FFT(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]

    if N <= 32:
        return DFT_slow(x)
    else:
        X_even = FFT(x[::2])
        X_odd = FFT(x[1::2])
        factor = np.exp(-2j * np.pi * np.arange(N) / N)
        return np.concatenate([X_even + factor[:N // 2] * X_odd,
                               X_even + factor[N // 2:] * X_odd])


def fft_2d(image):
    # Feita a FFT 1D em todas as linhas e, depois, colunas
    rows, cols = image.shape
    fft_result = np.zeros((rows, cols), dtype=np.complex128)
    for i in range(rows):
      fft_result[i] = FFT(image[i])
    for j in range(cols):
      fft_result[:,j] = FFT(fft_result[:,j])

    return fft_result


# Medição do tempo
start_time = time.time()
fft_result = fft_2d(image)
fft_time = time.time() - start_time

print(f"Tempo de execução da FFT 2D: {fft_time:.4f} segundos")

Tempo de execução da FFT 2D: 0.3491 segundos


<ipython-input-5-115a012ff843>:10: ComplexWarning: Casting complex values to real discards the imaginary part
  x = np.asarray(x, dtype=float)


Em execução prévia o algoritmo DFT 2D executou em aproximadamente 8760.3017 segundos e o FFT obteve um tempo de execução de 0.3491.


In [9]:
# Comparar os resultados (note que os valores podem ser complexos)
print("O tempo de execução do algoritmo FFT 2D foi aproximadamente ", 8760.3017//0.3491, " vezes menor que o tempo da DFT 2D")

A execução do algoritmo FFT 2D foi aproximadamente  25093.0  vezes mais rápida que DFT 2D
